// Converted from constants.ts — plain JavaScript without TypeScript types
export const PROVIDERS = {
  JIO: {
    name: 'JIO',
    displayName: 'Jio',
    gradient: 'from-blue-600 to-blue-700',
    shadow: 'shadow-blue-500/30',
    textColor: 'text-blue-600',
    buttonColor: 'bg-blue-600 hover:bg-blue-700',
    logoInitial: 'J',
  },
  AIRTEL: {
    name: 'AIRTEL',
    displayName: 'Airtel',
    gradient: 'from-red-600 to-red-700',
    shadow: 'shadow-red-500/30',
    textColor: 'text-red-600',
    buttonColor: 'bg-red-600 hover:bg-red-700',
    logoInitial: 'A',
  },
  VI: {
    name: 'VI',
    displayName: 'Vi',
    gradient: 'from-yellow-500 to-yellow-600',
    shadow: 'shadow-yellow-500/30',
    textColor: 'text-yellow-600',
    buttonColor: 'bg-yellow-500 hover:bg-yellow-600',
    logoInitial: 'V',
  },
  BSNL: {
    name: 'BSNL',
    displayName: 'BSNL',
    gradient: 'from-green-600 to-green-700',
    shadow: 'shadow-green-500/30',
    textColor: 'text-green-600',
    buttonColor: 'bg-green-600 hover:bg-green-700',
    logoInitial: 'B',
  },
};

const commonOtt = ['Disney+ Hotstar', 'Amazon Prime', 'Netflix Mobile'];

const generatePlans = (provider) => [
  {
    id: `${provider}_1`,
    price: 299,
    validity: '28 Days',
    data: '1.5 GB/Day',
    calls: 'Unlimited',
    sms: '100/Day',
    description: 'Best seller for monthly usage.',
    category: 'POPULAR',
  },
  {
    id: `${provider}_2`,
    price: 719,
    validity: '84 Days',
    data: '2 GB/Day',
    calls: 'Unlimited',
    sms: '100/Day',
    description: 'Truly Unlimited calls + Data.',
    category: 'POPULAR',
    ottBenefits: [commonOtt[0]],
  },
  {
    id: `${provider}_3`,
    price: 2999,
    validity: '365 Days',
    data: '2.5 GB/Day',
    calls: 'Unlimited',
    sms: '100/Day',
    description: 'Long term peace of mind.',
    category: 'ANNUAL',
    ottBenefits: [commonOtt[0], commonOtt[1]],
  },
  {
    id: `${provider}_4`,
    price: 15,
    validity: 'Active Plan',
    data: '1 GB',
    calls: 'NA',
    sms: 'NA',
    description: 'Data Booster Pack.',
    category: 'DATA_ONLY',
  },
  {
    id: `${provider}_5`,
    price: 10,
    validity: 'NA',
    data: 'NA',
    calls: '₹7.47 Talktime',
    sms: 'NA',
    description: 'Standard Top-up.',
    category: 'TOP_UP',
  },
  {
    id: `${provider}_6`,
    price: 479,
    validity: '56 Days',
    data: '1.5 GB/Day',
    calls: 'Unlimited',
    sms: '100/Day',
    description: 'Medium duration value pack.',
    category: 'POPULAR',
  },
  {
    id: `${provider}_7`,
    price: 155,
    validity: '24 Days',
    data: '1 GB Total',
    calls: 'Unlimited',
    sms: '300 Total',
    description: 'Entry level unlimited plan.',
    category: 'POPULAR',
  },
];

export const ALL_PLANS = {
  JIO: generatePlans('JIO'),
  AIRTEL: generatePlans('AIRTEL'),
  VI: generatePlans('VI'),
  BSNL: generatePlans('BSNL'),
};
